#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /accueil
    controller: App\Controller\EtudiantController::accueil
etudiantAjouter:
    path: /etudiant/ajouter
    controller: App\Controller\EtudiantController::ajouterEtudiant
etudiantConsulter:
    path: /etudiant/consulter/{idEtudiant}
    controller: App\Controller\EtudiantController::consulterEtudiant
etudiantLister:
    path: /etudiant/lister
    controller: App\Controller\EtudiantController::listerEtudiants